(function(g){var window=this;var uva=function(a,b){var c=[];g.El(b,function(a){try{var b=g.nD.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.mD(b)&&c.push(a):c.push(a)},a);
return c},vva=function(a,b){var c=uva(a,b);
(0,g.H)(c,function(a){g.nD.prototype.remove.call(this,a)},a)},i9=function(a,b){g.P0.call(this,g.T("YTP_MDX_TITLE"),0,a,b);
this.Z=a;this.F={};this.T(a,"onMdxReceiversChange",this.J);this.T(a,"presentingplayerstatechange",this.J);this.J()},wva=function(){var a=g.LG;
vva(a,a.g.Qd(!0))},j9=function(a){g.nH.call(this,"ScreenServiceProxy");
this.Yc=a;this.o=[];this.o.push(this.Yc.$_s("screenChange",(0,g.B)(this.OR,this)));this.o.push(this.Yc.$_s("onlineScreenChange",(0,g.B)(this.YN,this)))},k9=function(a){g.aH("cloudview",a)},xva=function(a){k9("setApiReady_ "+a);
g.v("yt.mdx.remote.cloudview.apiReady_",a,void 0)},l9=function(){return g.y("yt.mdx.remote.cloudview.instance_")},yva=function(a){g.cG[a]&&(a=g.cG[a],(0,g.H)(a,function(a){g.aG[a]&&delete g.aG[a]}),a.length=0)},m9=function(){return g.y("yt.mdx.remote.connection_")},n9=function(a){g.v("yt.mdx.remote.connectData_",a,void 0)},zva=function(a){g.v("yt.mdx.remote.currentScreenId_",a,void 0)},o9=function(){return g.y("yt.mdx.remote.currentScreenId_")},q9=function(){if(!p9){var a=g.y("yt.mdx.remote.screenService_");
p9=a?new j9(a):null}return p9},r9=function(a){g.v("yt.mdx.remote.cloudview.initializing_",a,void 0)},s9=function(){return!!g.y("yt.mdx.remote.cloudview.apiReady_")},t9=function(a){k9("setCastInstalled_ "+a);
g.NG("yt-remote-cast-installed",a)},u9=function(a){g.aH("cloudview",a)},Ava=function(a,b){l9().init(a,b)},v9=function(){return!!g.OG("yt-remote-cast-installed")},Bva=function(){k9("dispose");
var a=l9();a&&a.dispose();g.v("yt.mdx.remote.cloudview.instance_",null,void 0);xva(!1);g.eG(w9);w9.length=0},Cva=function(){var a=window.document.createElement("a");
g.Nd(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Ta(a)},Dva=function(a,b){var c=window.document.createElement("script");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
c.src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js";var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},Eva=function(a){var b=g.$F();
if(b)if(b.clear(a),a)yva(a);else for(var c in g.cG)yva(c)},x9=function(){return g.y("yt.mdx.remote.channelParams_")||{}},z9=function(a){var b=m9();
n9(null);a||zva("");g.v("yt.mdx.remote.connection_",a,void 0);y9&&((0,g.H)(y9,function(b){b(a)}),y9.length=0);
b&&!a?g.hG("yt-remote-connection-change",!1):!b&&a&&g.hG("yt-remote-connection-change",!0)},Fva=function(){return g.y("yt.mdx.remote.connectData_")},A9=function(){var a=o9();
if(!a)return null;var b=q9().Wd();return g.mH(b,a)},Gva=function(a,b){t9(!0);
r9(!1);Ava(a,function(a){a?(xva(!0),g.fG("yt-remote-cast2-api-ready")):(u9("Failed to initialize cast API."),t9(!1),g.PG("yt-remote-cast-available"),g.PG("yt-remote-cast-receiver"),Bva());b(a)})},Hva=function(){return v9()?l9()?l9().getCastSession():(u9("getCastSelector: Cast is not initialized."),null):(u9("getCastSelector: Cast API is not installed!"),null)},Iva=function(){var a=Cva(),b=window.document.getElementById(a),c=b&&g.qF(b,"loaded");
c||b&&!c||(b=Dva(a,function(){g.qF(b,"loaded")||(g.rF(b,"loaded","true"),g.fG(a),g.xE(g.ya(Eva,a),0))}))},Jva=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},Kva=function(){if(g.woa){var a=2,b=g.Dh(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;g.Ih("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",g.Fh,c)}},C9=function(a,b){o9();
A9()&&A9();zva(a.id);var c=new g.rI(B9,a,x9());c.connect(b,Fva());c.subscribe("beforeDisconnect",function(a){g.hG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){m9()&&(m9(),z9(null))});
z9(c)},D9=function(){var a=g.sH();
if(!a)return null;var b=q9().Wd();return g.mH(b,a)},E9=function(a){g.aH("remote",a)},F9=function(){var a=m9();
return!!a&&3!=a.getProxyState()},G9=function(){s9()?l9().stopSession():u9("stopSession called before API ready.");
var a=m9();a&&(a.disconnect(1),z9(null))},Lva=function(){var a=q9().Yc.$_gos();
var b=A9();b&&m9()&&(g.lH(a,b)||a.push(b));return Jva(a)},I9=function(a,b){g.RF.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.BB;this.A=this.o=null;this.J=(0,g.B)(this.fM,this);this.F=(0,g.B)(this.Lk,this);this.G=(0,g.B)(this.eM,this);this.K=(0,g.B)(this.sM,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Ss,this),Mva(this))):c=3;0!=c&&(b?this.Ss(c):g.xE((0,g.B)(function(){this.Ss(c)},this),0));
var d=Hva();d&&H9(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},J9=function(a){return new g.gI(a.B.getPlayerContextData())},Nva=function(a,b,c,d,e){var f=J9(a),k=e||f.listId;
d=d||0;var l={videoId:b,currentIndex:d};g.kI(f,b,d);g.t(c)&&(g.iI(f,c),l.currentTime=c);g.t(k)&&(l.listId=k);K9(a,"setPlaylist",l);e||L9(a,f)},Mva=function(a){(0,g.H)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.ya(this.sO,a),this))},a)},Ova=function(a){(0,g.H)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},M9=function(a,b){50>a.C.Lc()&&g.DB(a.C,b)},N9=function(a,b,c){var d=J9(a);
g.iI(d,c);-1E3!=d.g&&(d.g=b);L9(a,d)},K9=function(a,b,c){a.B.sendMessage(b,c)},L9=function(a,b){Ova(a);
a.B.setPlayerContextData(g.lI(b));Mva(a)},H9=function(a,b){a.A&&(a.A.removeUpdateListener(a.J),a.A.removeMediaListener(a.F),a.Lk(null));
a.A=b;a.A&&(O9("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.J),a.A.addMediaListener(a.F),a.A.media.length&&a.Lk(a.A.media[0]))},Pva=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=J9(a);b.contentId!=d.videoId&&O9("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.iI(d,a.o.getEstimatedTime());L9(a,d)}else O9("No cast media video. Ignoring state update.")},O9=function(a){g.aH("CP",a)},P9=function(a,b,c){return(0,g.B)(function(a){this.oc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.oc("Retrying "+b+" using MDx browser channel."),K9(this,b,c))},a)},Qva=function(a,b){var c=!1;
l9()||(c=new g.aI(a,b),c.subscribe("yt-remote-cast2-availability-change",function(a){g.NG("yt-remote-cast-available",a);g.hG("yt-remote-cast2-availability-change",a)}),c.subscribe("yt-remote-cast2-receiver-selected",function(a){k9("onReceiverSelected: "+a.friendlyName);
g.NG("yt-remote-cast-receiver",a);g.hG("yt-remote-cast2-receiver-selected",a)}),c.subscribe("yt-remote-cast2-receiver-resumed",function(a){k9("onReceiverResumed: "+a.friendlyName);
g.NG("yt-remote-cast-receiver",a)}),c.subscribe("yt-remote-cast2-session-change",function(a){k9("onSessionChange: "+g.iH(a));
a||g.PG("yt-remote-cast-receiver");g.hG("yt-remote-cast2-session-change",a)}),g.v("yt.mdx.remote.cloudview.instance_",c,void 0),c=!0);
k9("cloudview.createSingleton_: "+c);return c},Rva=function(){var a=0<=g.Gb.search(/\ (CrMo|Chrome|CriOS)\//);
return g.UE||a},Q9=function(a,b){s9()?l9().setConnectedScreenStatus(a,b):u9("setConnectedScreenStatus called before ready.")},Sva=function(){k9("clearCurrentReceiver");
g.PG("yt-remote-cast-receiver")},Tva=function(){if(0<=window.navigator.userAgent.indexOf("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){Kva();a({command:"cast.sender.init"});return}}if(window.chrome)if(Kva(),a=window.navigator.userAgent,0<=a.indexOf("Android")&&0<=a.indexOf("Chrome/")&&window.navigator.presentation){var a="",b=g.Bh();55<=b?a="55":50<=b&&(a="50");g.Ih("//www.gstatic.com/eureka/clank"+a+g.Gh,g.Fh)}else g.Jh(0);else g.Fh()},Uva=function(a){a?(g.NG("yt-remote-session-app",a.app),g.NG("yt-remote-session-name",a.name)):(g.PG("yt-remote-session-app"),g.PG("yt-remote-session-name"));
g.v("yt.mdx.remote.channelParams_",a,void 0)},Vva=function(){var a=x9();
if(g.Tb(a)){var a=g.rH(),b=g.OG("yt-remote-session-name")||"",c=g.OG("yt-remote-session-app")||"",a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.v("yt.mdx.remote.channelParams_",a,void 0)}},Wva=function(){var a=D9();
a?(E9("Resume connection to: "+g.iH(a)),C9(a,0)):(g.AH(),Sva(),E9("Skipping connecting because no session screen found."))},Xva=function(a){E9("remote.onCastSessionChange_: "+g.iH(a));
if(a){var b=A9();b&&b.id==a.id?Q9(b.id,"YouTube TV"):(b&&G9(),C9(a,1))}else m9()&&G9()},Yva=function(){var a=Lva(),b=A9();
b||(b=D9());return g.$a(a,function(a){return b&&g.fH(b,a.key)?!0:!1})},Zva=function(){var a=g.OG("yt-remote-cast-receiver");
return a?a.friendlyName:null},$va=function(a,b,c,d,e){Rva()?Qva(b,e)&&(r9(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?Gva(a,c):(window.__onGCastApiAvailable=function(b,d){b?Gva(a,c):(u9("Failed to load cast API: "+d),t9(!1),r9(!1),g.PG("yt-remote-cast-available"),g.PG("yt-remote-cast-receiver"),Bva(),c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):Iva():Tva())):k9("Cannot initialize because not running Chrome")},
awa=function(a){this.port=this.domain="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.vg(a)||"";b&&(this.port=":"+b);this.domain=g.ug(a)||"";a=g.Gb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Sa(a,"10.0")&&(this.o=!1))},bwa=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);
return c},R9=function(){var a=Yva();
!a&&v9()&&Zva()&&(a={key:"cast-selector-receiver",name:Zva()});return a},cwa=function(){var a=Lva();
v9()&&g.OG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},dwa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};g.LG&&wva();g.uH();B9||(B9=new awa,g.CH()&&(B9.g="/api/loungedev"));y9||(y9=g.y("yt.mdx.remote.deferredProxies_")||[],g.v("yt.mdx.remote.deferredProxies_",y9,void 0));Vva();var c=q9();if(!c){var d=new g.NH(B9);g.v("yt.mdx.remote.screenService_",d,void 0);c=q9();$va(a,d,function(a){a?o9()&&Q9(o9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){g.hG("yt-remote-receiver-availability-change")})},!(!b||!b.loadCastApiSetupScript),b?b.appId:void 0)}b&&!g.y("yt.mdx.remote.initialized_")&&
(g.v("yt.mdx.remote.initialized_",!0,void 0),E9("Initializing: "+g.Lc(b)),S9.push(g.dG("yt-remote-cast2-availability-change",function(){g.hG("yt-remote-receiver-availability-change")})),S9.push(g.dG("yt-remote-cast2-receiver-selected",function(){n9(null);
g.hG("yt-remote-auto-connect","cast-selector-receiver")})),S9.push(g.dG("yt-remote-cast2-receiver-resumed",function(){g.hG("yt-remote-receiver-resumed","cast-selector-receiver")})),S9.push(g.dG("yt-remote-cast2-session-change",Xva)),S9.push(g.dG("yt-remote-connection-change",function(a){a?Q9(o9(),"YouTube TV"):D9()||(Q9(null,null),Sva())})),a=x9(),b.isAuto&&(a.id+="#dial"),g.aF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,E9(" -- with channel params: "+g.Lc(a)),
Uva(a),c.start(),o9()||Wva())},T9=function(){v9()?l9()?s9()?(k9("Requesting cast selector."),l9().requestSession()):(k9("Wait for cast API to be ready to request the session."),w9.push(g.dG("yt-remote-cast2-api-ready",T9))):u9("requestCastSelector: Cast is not initialized."):u9("requestCastSelector: Cast API is not installed!")},U9=function(a,b,c){g.M.call(this);
this.F=a;this.Z=b;this.o=new g.CJ(this);g.N(this,this.o);this.o.T(b,"onCaptionsTrackListChanged",this.rN);this.o.T(b,"captionschanged",this.dM);this.o.T(b,"captionssettingschanged",this.SA);this.o.T(b,"videoplayerreset",this.xn);this.o.T(b,"mdxautoplaycancel",this.sF);this.O=this.o.T(b,"onVolumeChange",this.nz);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.Az,this);c.subscribe("remotePlayerChange",this.Nk,this);c.subscribe("remoteQueueChange",this.xn,this);c.subscribe("autoplayUpNext",this.Zy,
this);c.subscribe("previousNextChange",this.xz,this);c.subscribe("nowAutoplaying",this.oz,this);c.subscribe("autoplayDismissed",this.Yy,this);this.suggestion=null;this.G=new g.WJ(64);this.A=new g.qt(this.NA,500,this);g.N(this,this.A);this.B=new g.qt(this.OA,1E3,this);g.N(this,this.B);this.C={};this.K=new g.qt(this.dB,1E3,this);g.N(this,this.K);this.J=new g.dk(this.gK,1E3,this);g.N(this,this.J);this.M=g.z;this.SA();this.xn();this.Nk()},V9=function(a,b){var c=a.F,d=a.Z.ia().lengthSeconds;
c.J=b||0;c.g.X("progresssync",b,d)},ewa=function(a){V9(a,0);
a.A.stop();W9(a,new g.WJ(64))},Y9=function(a,b){if(X9(a)&&!a.D){var c=null;
b&&(c={style:a.Z.Dk()},g.ac(c,b));a.g.HA(a.Z.ia().videoId,c);a.C=J9(a.g).o}},Z9=function(a,b){var c=a.Z.If();
c?Nva(a.g,a.Z.ia().videoId,b,c.Ud(),c.listId.toString()):Nva(a.g,a.Z.ia().videoId,b);W9(a,new g.WJ(1))},fwa=function(a,b){if(b){var c=a.Z.Zc("captions","tracklist",{Rw:1});
c&&c.length?(a.Z.Ge("captions","track",b),a.D=!1):(a.Z.Bk("captions"),a.D=!0)}else a.Z.Ge("captions","track",{})},X9=function(a){return J9(a.g).videoId==a.Z.ia().videoId},W9=function(a,b){a.B.stop();
var c=a.G;if(!g.bK(c,b)){var d=g.V(b,2);if(d!=g.V(a.G,2)){var e=a.Z;g.$1(e.app,d,e.playerType)}a.G=b;gwa(a.F,c,b)}},$9=function(a){g.W.call(this,{H:"div",
N:"ytp-remote",L:[{H:"div",N:"ytp-remote-display-status",L:[{H:"div",N:"ytp-remote-display-status-icon",L:[g.SD()]},{H:"div",N:"ytp-remote-display-status-text",L:["{{statustext}}"]}]}]});this.o=new g.GV(this,250);g.N(this,this.o);this.A=a;this.T(a,"presentingplayerstatechange",this.B);hwa(this,g.UU(a))},hwa=function(a,b){if(3==a.A.Ya()){var c={RECEIVER_NAME:a.A.Zc("remote","currentReceiver").name},c=g.V(b,128)?g.T("YTP_MDX_STATUS_ERROR_2",c):b.wb()||g.V(b,4)?g.T("YTP_MDX_STATUS_PLAYING_2",c):g.T("YTP_MDX_STATUS_CONNECTED_2",
c);
a.Ca("statustext",c);a.o.show()}else a.o.hide()},a$=function(a){g.vV.call(this,a);
this.A={key:g.kH(),name:g.T("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.K=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.WJ(64);this.J=0;var b=g.NU(a).D;b&&(b=b.A&&b.A.g)&&(b=new i9(a,b),g.N(this,b));b=new $9(a);g.N(this,b);g.kV(a,b.element,5)},gwa=function(a,b,c){a.F=c;
a.g.X("presentingplayerstatechange",new g.gK(c,b))},b$=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)G9();
else{a.B=b;var c=a.g.getPlaylistId();var d=a.g.ia().videoId;if(c||d){var e=a.g.If();if(e){var f=[];for(var k=0;k<e.getLength();k++)f[k]=e.gc(k).videoId}else f=[a.g.ia().videoId];c={videoIds:f,listId:c,videoId:d,index:Math.max(a.g.Gx(),0),currentTime:a.g.getCurrentTime()}}else c=null;E9("Connecting to: "+g.Lc(b));"cast-selector-receiver"==b.key?(n9(c||null),c=c||null,s9()?l9().setLaunchParams(c):u9("setLaunchParams called before ready.")):!c&&F9()&&o9()==b.key?g.hG("yt-remote-connection-change",!0):
(G9(),n9(c||null),c=q9().Wd(),(c=g.mH(c,b.key))&&C9(c,1))}};
g.p(i9,g.P0);i9.prototype.J=function(){var a=this.Z.Zc("remote","receivers");a&&1<a.length&&!this.Z.Zc("remote","quickCast")?(this.F=g.Cb(a,this.B,this),g.R0(this,(0,g.I)(a,this.B)),a=this.Z.Zc("remote","currentReceiver"),g.Q0(this,this.B(a)),this.enable(!0)):this.enable(!1)};
i9.prototype.B=function(a){return a.key};
i9.prototype.Pe=function(a){return"cast-selector-receiver"==a?g.T("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
i9.prototype.ld=function(a){g.P0.prototype.ld.call(this,a);this.Z.Ge("remote","currentReceiver",this.F[a]);this.A.bc()};
g.C(j9,g.nH);g.h=j9.prototype;g.h.Wd=function(a){return this.Yc.$_gs(a)};
g.h.contains=function(a){return!!this.Yc.$_c(a)};
g.h.get=function(a){return this.Yc.$_g(a)};
g.h.start=function(){this.Yc.$_st()};
g.h.ro=function(a,b,c){this.Yc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Yc.$_r(a,b,c)};
g.h.ao=function(a,b,c,d){this.Yc.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.o.length;a<b;++a)this.Yc.$_ubk(this.o[a]);this.o.length=0;this.Yc=null;j9.Y.V.call(this)};
g.h.OR=function(){this.X("screenChange")};
g.h.YN=function(){this.X("onlineScreenChange")};
var p9=null,w9=[],y9=null,B9=null;g.C(I9,g.RF);g.h=I9.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.z,P9(this,"play")):K9(this,"play"),N9(this,1,g.jI(J9(this))),this.X("remotePlayerChange")):M9(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.z,P9(this,"pause")):K9(this,"pause"),N9(this,2,g.jI(J9(this))),this.X("remotePlayerChange")):M9(this,this.pause)};
g.h.nB=function(a){if(1==this.g){if(this.o){var b=J9(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.wb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.z,P9(this,"seekTo",{newTime:a}))}else K9(this,"seekTo",{newTime:a});N9(this,3,a);this.X("remotePlayerChange")}else M9(this,g.ya(this.nB,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.z,P9(this,"stopVideo")):K9(this,"stopVideo");var a=J9(this);a.index=-1;a.videoId="";g.hI(a);L9(this,a);this.X("remotePlayerChange")}else M9(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=J9(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.B)(function(){O9("set receiver volume: "+d)},this),(0,g.B)(function(){this.oc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.B)(function(){O9("set receiver muted: "+b)},this),(0,g.B)(function(){this.oc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);K9(this,"setVolume",e)}c.muted=b;c.volume=a;L9(this,c)}else M9(this,g.ya(this.setVolume,a,b))};
g.h.HA=function(a,b){if(1==this.g){var c=J9(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Lc(b.style),g.ac(d,c.o));K9(this,"setSubtitlesTrack",d);L9(this,c)}else M9(this,g.ya(this.HA,a,b))};
g.h.Rs=function(a,b){if(1==this.g){K9(this,"setAudioTrack",{videoId:a,audioTrackId:b.Qc.id});var c=J9(this);c.audioTrackId=b.Qc.id;L9(this,c)}else M9(this,g.ya(this.Rs,a,b))};
g.h.mB=function(a,b){if(1==this.g){if(a&&b){var c=J9(this);g.kI(c,a,b);L9(this,c)}K9(this,"previous")}else M9(this,g.ya(this.mB,a,b))};
g.h.lB=function(a,b){if(1==this.g){if(a&&b){var c=J9(this);g.kI(c,a,b);L9(this,c)}K9(this,"next")}else M9(this,g.ya(this.lB,a,b))};
g.h.vv=function(){1==this.g?K9(this,"dismissAutoplay"):M9(this,this.vv)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.X("proxyStateChange",a,this.g)}I9.Y.dispose.call(this)};
g.h.V=function(){Ova(this);this.B=null;this.C.clear();H9(this,null);I9.Y.V.call(this)};
g.h.Ss=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.X("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.EB(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.sO=function(a,b){this.X(a,b)};
g.h.fM=function(a){if(!a)this.Lk(null),H9(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=J9(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)O9("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,L9(this,b)}};
g.h.Lk=function(a){O9("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),Pva(this),this.X("remotePlayerChange")};
g.h.eM=function(a){a?(Pva(this),this.X("remotePlayerChange")):this.Lk(null)};
g.h.sM=function(){var a=Hva();a&&H9(this,a)};
g.h.oc=function(a){g.aH("CP",a)};
var S9=[];g.h=awa.prototype;g.h.Lh=function(a,b,c){var d=this.g;if(g.t(c)?c:this.o)d="https://"+this.domain+this.port+this.g;return g.Dg(d+a,b||{})};
g.h.Qs=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Mb:g.ya(this.JR,c,!0),onError:g.ya(this.IR,d),cd:g.ya(this.KR,d)};b&&(c.Qb=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.KE(a,c)};
g.h.JR=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.IR=function(a,b){a(Error("Request error: "+b.status))};
g.h.KR=function(a){a(Error("request timed out"))};
g.p(U9,g.M);g.h=U9.prototype;g.h.V=function(){g.M.prototype.V.call(this);this.A.stop();this.B.stop();this.M();this.g.unsubscribe("proxyStateChange",this.Az,this);this.g.unsubscribe("remotePlayerChange",this.Nk,this);this.g.unsubscribe("remoteQueueChange",this.xn,this);this.g.unsubscribe("autoplayUpNext",this.Zy,this);this.g.unsubscribe("previousNextChange",this.xz,this);this.g.unsubscribe("nowAutoplaying",this.oz,this);this.g.unsubscribe("autoplayDismissed",this.Yy,this);this.g=this.F=null};
g.h.Zx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(X9(this)){if(1081!=J9(this.g).g||"control_seek"!=a)switch(a){case "control_toggle_play_pause":J9(this.g).wb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.J.Ri(c[0],c[1]);break;case "control_subtitles_set_track":Y9(this,c[0]);break;case "control_set_audio_track":c=c[0],X9(this)&&this.g.Rs(this.Z.ia().videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":Z9(this,this.Z.getCurrentTime());break;case "control_seek":Z9(this,c[0]);break;case "control_subtitles_set_track":Y9(this,c[0]);break;case "control_set_audio_track":c=c[0],X9(this)&&this.g.Rs(this.Z.ia().videoId,c)}};
g.h.dM=function(a){this.Zx("control_subtitles_set_track",g.Tb(a)?null:a)};
g.h.SA=function(){var a=this.Z.Zc("captions","track");g.Tb(a)||Y9(this,a)};
g.h.nz=function(a){if(X9(this)){this.g.unsubscribe("remotePlayerChange",this.Nk,this);var b=Math.round(a.volume);a=!!a.muted;var c=J9(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.K.start();this.g.subscribe("remotePlayerChange",this.Nk,this)}};
g.h.rN=function(){g.Tb(this.C)||fwa(this,this.C);this.D=!1};
g.h.Az=function(a,b){this.B.stop();2==b&&this.OA()};
g.h.Nk=function(){if(X9(this)){this.A.stop();var a=J9(this.g);switch(a.g){case 1081:W9(this,new g.WJ(8));break;case 1:this.NA();W9(this,new g.WJ(8));break;case 1083:case 3:W9(this,new g.WJ(9));break;case 0:W9(this,new g.WJ(2));this.J.stop();V9(this,this.Z.ia().lengthSeconds);break;case 1082:W9(this,new g.WJ(4));break;case 2:W9(this,new g.WJ(4));V9(this,g.jI(a));break;case -1:W9(this,new g.WJ(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.T("YTP_MDX_PLAYER_ERROR")},W9(this,new g.WJ(128,
a))}var a=J9(this.g).o,b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,fwa(this,a));a=J9(this.g);-1==a.volume||Math.round(this.Z.getVolume())==a.volume&&this.Z.Fe()==a.muted||this.K.isActive()||this.dB()}else ewa(this)};
g.h.xz=function(){this.Z.X("mdxpreviousnextchange")};
g.h.xn=function(){X9(this)||ewa(this)};
g.h.sF=function(){this.g.vv()};
g.h.Zy=function(a){a&&(a=g.KE("/watch_queue_ajax",{method:"GET",Uc:{action_get_watch_queue_item:1,video_id:a},Mb:(0,g.B)(this.tP,this)}))&&(this.M=(0,g.B)(a.abort,a))};
g.h.tP=function(a,b){var c=new g.qQ({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.Z.X("mdxautoplayupnext",c)};
g.h.oz=function(a){(0,window.isNaN)(a)||this.Z.X("mdxnowautoplaying",a)};
g.h.Yy=function(){this.Z.X("mdxautoplaycanceled")};
g.h.gK=function(a,b){-1==J9(this.g).g?Z9(this,a):b&&this.g.nB(a)};
g.h.dB=function(){if(X9(this)){var a=J9(this.g);this.o.Aa(this.O);a.muted?this.Z.mute():this.Z.qg();this.Z.setVolume(a.volume);this.O=this.o.T(this.Z,"onVolumeChange",this.nz)}};
g.h.NA=function(){this.A.stop();if(!this.g.na()){var a=J9(this.g);a.wb()&&W9(this,new g.WJ(8));V9(this,g.jI(a));this.A.start()}};
g.h.OA=function(){this.B.stop();this.A.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p($9,g.W);$9.prototype.B=function(a){hwa(this,a.state)};g.p(a$,g.vV);g.h=a$.prototype;g.h.create=function(){dwa("embedded"==g.Y(this.g).g);this.D.push(g.dG("yt-remote-before-disconnect",this.aM,this));this.D.push(g.dG("yt-remote-connection-change",this.CO,this));this.D.push(g.dG("yt-remote-receiver-availability-change",this.yz,this));this.D.push(g.dG("yt-remote-auto-connect",this.AO,this));this.D.push(g.dG("yt-remote-receiver-resumed",this.zO,this));this.yz()};
g.h.load=function(){this.g.kp();g.vV.prototype.load.call(this);this.C=new U9(this,this.g,this.o);var a=Fva(),a=a?a.currentTime:0,b=F9()?new I9(m9(),void 0):null;0==a&&b&&(a=g.jI(J9(b)));0!=a&&(this.J=a||0,this.g.X("progresssync",a,void 0));gwa(this,this.F,this.F);g.f2(this.g.app,6)};
g.h.unload=function(){this.g.X("mdxautoplaycanceled");this.B=this.A;g.Se(this.C,this.o);this.o=this.C=null;g.vV.prototype.unload.call(this);g.f2(this.g.app,5)};
g.h.V=function(){g.eG(this.D);g.vV.prototype.V.call(this)};
g.h.Gk=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.Zx.apply(this.C,[].concat([a],c instanceof Array?c:bwa(g.ka(c))))};
g.h.eG=function(){return this.loaded?this.C.suggestion:null};
g.h.Bf=function(){return this.o?J9(this.o).Bf:!1};
g.h.hasNext=function(){return this.o?J9(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.J};
g.h.YJ=function(){var a=J9(this.o),b=this.g.ia();return{allowSeeking:this.g.Id(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.F?a.C+((0,g.G)()-a.A)/1E3:a.C,isPeggedToLive:1>=(a.F?a.B+((0,g.G)()-a.A)/1E3:a.B)-this.getCurrentTime(),loaded:a.K,seekableEnd:a.F?a.B+((0,g.G)()-a.A)/1E3:a.B,seekableStart:0<a.D?a.D+((0,g.G)()-a.A)/1E3:a.D}};
g.h.ZJ=function(){this.o&&this.o.lB()};
g.h.aK=function(){this.o&&this.o.mB()};
g.h.aM=function(a){1==a&&(this.K=this.o?J9(this.o):null)};
g.h.CO=function(){var a=F9()?new I9(m9(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.K=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Re(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.g.ia().videoId&&this.g.Dx(a.videoId,g.jI(a)));this.g.X("videodatachange","newdata",this.g.ia(),3)};
g.h.yz=function(){this.G=[this.A].concat(cwa());var a=R9()||this.A;b$(this,a);this.g.ya("onMdxReceiversChange")};
g.h.AO=function(){var a=R9();b$(this,a)};
g.h.zO=function(){this.B=R9()};
g.h.XJ=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?T9():b$(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&T9(),!0):!1}};
g.h.bK=function(){K9(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.yd=function(){return!1};window._exportCheck==g.Ba&&g.v("ytmod.player.remote",a$,void 0);})(_yt_player);
